version: '3.4'
#NB: -port: host_port:container_port

networks:
  mynetwork:
    external: true
      
services:

  ###################
  # kong-database now postgresqlKong containerHost in another docker-compose.yml
  # with POSTGRES_USER: kong , POSTGRES_PASSWORD: kong and dbname=kong
  ###################
  
  #######################################
  # Kong database migration (initialisation)
  # it's just for FIRST-START !!!!
  #######################################
  kong-migration:
    image: kong:3.2.2-ubuntu
    command: "kong migrations bootstrap --v --vv"
    networks:
      - mynetwork
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresqlKong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong  
     
      
  
   
