version: '3.4'
# with docker-compose 2.1 depends-on with condition like service_healthy
# since docker-compose 3 depends-on with no more condition
# since version 3 , needs to ajust healthcheck/interval,timeout,retries
# healthcheck/start_period depuis v4.3

networks:
  mynetwork:
    external: true
    
services:

  jenkins:
    #image: jenkins/jenkins:lts
    build : ./custom-jenkins
    privileged: true
    user: root
    ports:
      - 8998:8080
      - 50000:50000
    container_name: jenkins-cicd
    volumes:
      #- /vagrant/jenkins-data:/var/jenkins_home
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker 
      - /vagrant/conf-docker:/conf-docker
 
 
