
networks:
  mynetwork:
    external: true
    
# ../secrets/.mongo_secret_pwd (NOT IN GIT !!!) 
# should contains mongoDB password (root or otherValue)   
secrets:
  mongo_secret_pwd:
    file: ../secrets/.mongo_secret_pwd     
    
services:
      
  tp-api:
    #build : ../../local-git-repositories/tp-api
    image: didierdefrance69/tp_api:1
    restart: always
    container_name: backend-tp-api
    secrets:
      - mongo_secret_pwd
    environment:
      PORT : 8233
      #MONGODB_URL: mongodb://root:root@mongoDB.host:27017
      MONGODB_HOSTNAME: mongoDB.host
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      #MONGODB_PASSWORD: root
      MONGODB_PASSWORD_FILE: /run/secrets/mongo_secret_pwd
    networks:
      mynetwork:
        aliases:
          - backend-tp-api.api.host
          - backend-tp-api.api.service
    ports:
      - "8233:8233"
    extra_hosts:
      - "host.docker.internal:host-gateway"
