
networks:
  mynetwork:
    external: true
    
# ../secrets/.mongo_secret_pwd (NOT IN GIT !!!) 
# should contains mongoDB password (root or otherValue)   
secrets:
  mongo_secret_pwd:
    file: ../secrets/.mongo_secret_pwd       
    
services:
      
  ddc-api:
    #build : ../../local-git-repositories/ddc-api
    image: didierdefrance69/ddc_api:1
    container_name: backend-ddc-api
    restart: always
    secrets:
      - mongo_secret_pwd
    environment:
      PORT : 8231
      #MONGODB_URL: mongodb://root:root@mongoDB.host:27017
      MONGODB_HOSTNAME: mongoDB.host
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      #MONGODB_PASSWORD: root
      MONGODB_PASSWORD_FILE: /run/secrets/mongo_secret_pwd
    volumes:
      - /var/my-docker-volumes/ddc-app-posts:/usr/src/app/html/mnt_posts
      # /var/my-docker-volumes/ddc-app-posts needs to be prepared with with subdirectory images
    networks:
      mynetwork:
        aliases:
          - backend-ddc-api.api.host
          - backend-ddc-api.api.service
    ports:
      - "8231:8231"
      