version: '3.4'
# with docker-compose 2.1 depends-on with condition like service_healthy
# since docker-compose 3 depends-on with no more condition
# since version 3 , needs to ajust healthcheck/interval,timeout,retries
# healthcheck/start_period depuis v4.3

networks:
  mynetwork:
    external: true
    
services:
      
  ddc-api:
    build : ../../docker-contents/ddc-api
#   image: xyz/backend-customer-repo
    container_name: backend-ddc-api
    environment:
      PORT : 8231
      MONGODB_URL: mongodb://root:root@mongoDB.host:27017
    networks:
      mynetwork:
        aliases:
          - backend-ddc-api.api.host
          - backend-ddc-api.api.service
    ports:
      - "8231:8231"
    volumes:
      - ../../docker-contents/ddc-api:/usr/src/app
      