version: '3.4'
#NB: -port: host_port:container_port

networks:
  kong-net:
    driver: bridge
  mynetwork:
    external: true
      
services:

  ###################
  # kong-database
  ###################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 3
      
  #######################################
  # Kong database migration (initialisation)
  #######################################
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PASSWORD: kong
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    links:
      - kong-database
    depends_on:
      - kong-database    
      
  #######################################
  # kong-gateway : The API Gateway
  #  KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl works but KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443 not working !!!!???
  #  without certificates , need --insecure of curl (self signed certificates by default)  
  #######################################
  kong-gateway:
    image: kong:latest
    restart: always
    container_name: kong-gateway
    networks:
      kong-net:
        aliases:
          - kong-gateway
          - d2fc.d-defrance.fr
      mynetwork:
        aliases:
          - kong-gateway
          - d2fc.d-defrance.fr
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_SSL: "on"
      # ssl config
      #KONG_SSL_CERT: /certs/certificate.crt
      #KONG_SSL_CERT_KEY: /certs/certificate.key
      #KONG_ADMIN_SSL_CERT: /certs/certificate.crt
      #KONG_ADMIN_SSL_CERT_KEY: /certs/certificate.key
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 20s
      timeout: 20s
      retries: 10
    ports:
      - "8001:8001"
      - "80:8000"
      - "8443:8443"
      - "8444:8444"
    #volumes:
     # - ./certs:/certs
   
