version: '3.4'
#NB: -port: host_port:container_port

networks:
  mynetwork:
    external: true
      
services:

  ###################
  # kong-database now postgresqlKong containerHost in another docker-compose.yml
  # with POSTGRES_USER: kong , POSTGRES_PASSWORD: kong and dbname=kong
  ###################

  
  #######################################
  # kong-gateway : The API Gateway
  #  KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl works but KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443 not working !!!!???
  #  without certificates , need --insecure of curl (self signed certificates by default)  
  #######################################
  kong-gateway:
    image: kong:3.2.2-ubuntu
    command: "kong --v --vv"
    restart: always
    container_name: kong-gateway
    networks:
      mynetwork:
        aliases:
          - kong-gateway
          - d2fc.d-defrance.fr
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresqlKong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_SSL: "on"
      # ssl config
      #KONG_SSL_CERT: /certs/certificate.crt
      KONG_SSL_CERT: /certs/certificate.pem
      KONG_SSL_CERT_KEY: /certs/certificate.key
      #KONG_ADMIN_SSL_CERT: /certs/certificate.crt
      KONG_ADMIN_SSL_CERT: /certs/certificate.pem
      KONG_ADMIN_SSL_CERT_KEY: /certs/certificate.key
    ports:
      #- "8000:8000"
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "8444:8444"
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://kong:8001"]
      #interval: 20s
      #timeout: 20s
      #retries: 10
    volumes:
      - /var/certs:/certs
   
