#memo
#NB: -port: host_port:container_port
# ${VAR_NAME:-defaultvalueIfNotSetAndNotEmpty}
# ${ROOT_USERNAME} (empty by default) may be override with .env file (ROOT_USERNAME=rootOrOtherValue)
#NB: dans future V2 , améliorer via volumes et sauvegardes

networks:
  mynetwork:
    external: true
   
# ../secrets/.mongo_secret_pwd (NOT IN GIT !!!) 
# should contains mongoDB password (root or otherValue)   
secrets:
  mongo_secret_pwd:
    file: ../secrets/.mongo_secret_pwd  
      
services:

  ###################
  # mongoDB server
  # url: mongodb://root:root@mongoDB_or_localhost:27017/
  # 8.0.12 multi-platform : ok on vps ubuntu 22.04 and wls2
  ###################
  mongo:
    image: mongo:8.0.12
    restart: always
    container_name: mongoDB
    secrets:
      - mongo_secret_pwd
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_USERNAME: "${ROOT_USERNAME:-root}"
      #MONGO_INITDB_ROOT_PASSWORD: root
      #MONGO_INITDB_ROOT_PASSWORD: "${ROOT_PWD:-root}"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_secret_pwd
    ports:
      - 27017:27017
    volumes:
      - /var/my-docker-volumes/mongo/data/db:/data/db
      - /var/my-docker-volumes/mongo/data/configdb:/data/configdb
    networks:
      mynetwork:
        aliases:
          - mongoDB.server.host
          - mongoDB.host
          - mongoDB