version: '3.4'
#NB: -port: host_port:container_port

networks:
  mynetwork:
    external: true
      
services:

  ###################
  # keycloak server
  # NB: CPU does not support x86-64-v2 with 21.0.1 , no problem with 20.0.3 and below
  # NB: --proxy edge signifie https du client au reverse-proxy puis http du reverse-proxy à keycloak
  # NB: --hostname-url=http://localhost:80/keycloak ou autre très importante
  # pour que les redirections et que le contenu de /.well-known/openid-configuration
  # soient cohérents vis à vis de l'url d'accès à keycloak sur le reverse-proxy / api-gateway)
  ###################
  keycloakauth:
    #image: quay.io/keycloak/keycloak:21.0.1
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - "8989:8989"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin 
      #PROXY_ADDRESS_FORWARDING=true
      #VIRTUAL_HOST=dev-keycloak.mydomain.com
      #VIRTUAL_PORT=8080
      #LETSENCRYPT_HOST=dev-keycloak.mydomain.com
      
    command: 
      - start-dev 
      - --http-port=8989
      - --proxy edge
      - --hostname-strict=false
      - --hostname-url=http://localhost:80/keycloak
      # - start
      - --db=postgres
      # - --features=token-exchange
      - --db-url=jdbc:postgresql://postgresqlKeycloak.host:5432/keycloak
      - --db-username=keycloak
      - --db-password=keycloak
      # - --https-key-store-file=server.keystore 
      # - --https-key-store-password=secret
    #volumes:
     # - /base/my-docker-volumes/keycloak/data:/opt/keycloak/data
    networks:
      mynetwork:
        aliases:
          - keycloakauth.server.host
          - keycloakauth.host
          - keycloakauth 
    extra_hosts:
      - "host.docker.internal:host-gateway"
