version: '3.4'
#NB: -port: host_port:container_port

networks:
  mynetwork:
    external: true
      
services:

  ###################
  # keycloak server
  # NB: CPU does not support x86-64-v2 with 21.0.1 , no problem with 20.0.3 and below
  ###################
  keycloakAuth:
    #image: quay.io/keycloak/keycloak:21.0.1
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - "8989:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin 
      #PROXY_ADDRESS_FORWARDING=true
      #VIRTUAL_HOST=dev-keycloak.mydomain.com
      #VIRTUAL_PORT=8080
      #LETSENCRYPT_HOST=dev-keycloak.mydomain.com
      
    command: 
      - start-dev 
      # - start
    volumes:
    volumes:
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
     # - /base/my-docker-volumes/keycloak/data:/opt/keycloak/data
    networks:
      mynetwork:
        aliases:
          - keycloakAuth.server.host
          - keycloakAuth.host
          - keycloakAuth 
