version: '3.4'
# with docker-compose 2.1 depends-on with condition like service_healthy
# since docker-compose 3 depends-on with no more condition
# since version 3 , needs to ajust healthcheck/interval,timeout,retries
# healthcheck/start_period depuis v4.3

networks:
  mynetwork:
    external: true
    
services:
      
  qcm-api:
    build : ../../docker-contents/user-api
#   image: xyz/backend-user-api
    container_name: backend-user-api
    environment:
      PORT : 8232
      MONGODB_URL: mongodb://root:root@mongoDB.host:27017
    networks:
      mynetwork:
        aliases:
          - backend-user-api.api.host
          - backend-user-api.api.service
    ports:
      - "8232:8232"