
networks:
  mynetwork:
    external: true
    
# ../secrets/.mongo_secret_pwd (NOT IN GIT !!!) 
# should contains mongoDB password (root or otherValue)   
secrets:
  mongo_secret_pwd:
    file: ../secrets/.mongo_secret_pwd         
    
services:
      
  qcm-api:
    build : ../../local-git-repositories/user-api
#   image: xyz/backend-user-api
    restart: always
    container_name: backend-user-api
    secrets:
      - mongo_secret_pwd
    environment:
      PORT : 8232
      #MONGODB_URL: mongodb://root:root@mongoDB.host:27017
      MONGODB_HOSTNAME: mongoDB.host
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      #MONGODB_PASSWORD: root
      MONGODB_PASSWORD_FILE: /run/secrets/mongo_secret_pwd
    networks:
      mynetwork:
        aliases:
          - backend-user-api.api.host
          - backend-user-api.api.service
    ports:
      - "8232:8232"