
networks:
  mynetwork:
    external: true
    
# ../secrets/.mongo_secret_pwd (NOT IN GIT !!!) 
# should contains mongoDB password (root or otherValue)   
secrets:
  mongo_secret_pwd:
    file: ../secrets/.mongo_secret_pwd     
    
services:
      
  qcm-api:
    #build : ../../local-git-repositories/qcm-api
    image: didierdefrance69/qcm_api:1
    container_name: backend-qcm-api
    restart: always
    secrets:
      - mongo_secret_pwd
    environment:
      PORT : 8230
      #MONGODB_URL: mongodb://root:root@mongoDB.host:27017
      MONGODB_HOSTNAME: mongoDB.host
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      #MONGODB_PASSWORD: root
      MONGODB_PASSWORD_FILE: /run/secrets/mongo_secret_pwd
    networks:
      mynetwork:
        aliases:
          - backend-qcm-api.api.host
          - backend-qcm-api.api.service
    ports:
      - "8230:8230"