version: '3.4'
#Rappel: -p host_port:container_port

networks:
  mynetwork:
    external: true
    
services:
      
  qcm-app:
    #build : ../../local-git-repositories/qcm-app
    image: didierdefrance69/qcm_app:1
    container_name: frontend-qcm-app
    restart: always
    environment:
      PORT : 4000
    networks:
      mynetwork:
        aliases:
          - qcm-app.frontend
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"